import { existsSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import {
  VXKEX_NEXT_INSTALLED_VERSION,
  VXKEX_NEXT_SETUP,
  VXKEX_NEXT_URL,
  VXKEX_NEXT_VERSION,
  bundledVxKexPath,
  prepareBundledVxKex,
} from '../scripts/vxkex-next.ts'
import {
  VC_REDIST_SHA256,
  VC_REDIST_URL,
  VC_REDIST_VERSION,
  isWindows7VcRedist,
  parseFileVersion,
  prepareWindows7VcRedist,
  renderWindows7PayloadInclude,
  type VcRedistHost,
} from '../scripts/windows7-offline-payload.ts'

const roots: string[] = []
afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true })
})

function temporary(): string {
  const root = mkdtempSync(join(tmpdir(), 'workdsh-win7-payload-'))
  roots.push(root)
  return root
}

describe('pinned VxKex NEXT setup', () => {
  it('pins one release asset and its InstalledVersion encoding', () => {
    expect(VXKEX_NEXT_SETUP).toBe(`KexSetup_Release_${VXKEX_NEXT_VERSION.replaceAll('.', '_')}.exe`)
    expect(VXKEX_NEXT_URL).toBe(`https://github.com/YuZhouRen86/VxKex-NEXT/releases/download/${VXKEX_NEXT_VERSION}/${VXKEX_NEXT_SETUP}`)
    expect(VXKEX_NEXT_INSTALLED_VERSION).toBe(0x8000099f)
  })

  it('rejects downloaded bytes that do not match the pinned digest', async () => {
    const root = temporary()
    const urls: string[] = []

    await expect(prepareBundledVxKex(root, async (url) => {
      urls.push(url)
      return Buffer.from('not the VxKex NEXT setup')
    })).rejects.toThrow(/checksum mismatch/u)

    expect(urls).toEqual([VXKEX_NEXT_URL])
    expect(existsSync(bundledVxKexPath(root))).toBe(false)
  })
})

describe('Windows 7 VC++ redistributable', () => {
  it('parses Windows file versions', () => {
    expect(parseFileVersion('14.44.35211.0')).toEqual({ major: 14, minor: 44, build: 35211, revision: 0 })
    expect(parseFileVersion('14.29.30153')).toEqual({ major: 14, minor: 29, build: 30153, revision: 0 })
    expect(() => parseFileVersion('14.44')).toThrow(/Invalid/u)
  })

  it('accepts only the v14 series that still installs on Windows 7', () => {
    expect(isWindows7VcRedist(parseFileVersion('14.29.30153.0'))).toBe(true)
    expect(isWindows7VcRedist(parseFileVersion('14.44.35211.0'))).toBe(true)
    expect(isWindows7VcRedist(parseFileVersion('14.28.29914.0'))).toBe(false)
    expect(isWindows7VcRedist(parseFileVersion('14.50.35710.0'))).toBe(false)
  })

  it('pins the last Visual Studio 2022-stream redistributable by its Microsoft URL', () => {
    expect(VC_REDIST_VERSION).toBe('14.44.35211.0')
    expect(isWindows7VcRedist(parseFileVersion(VC_REDIST_VERSION))).toBe(true)
    expect(VC_REDIST_URL).toBe(
      `https://download.visualstudio.microsoft.com/download/pr/7ebf5fdb-36dc-4145-b0a0-90d3d5990a61/${VC_REDIST_SHA256.toUpperCase()}/VC_redist.x64.exe`,
    )
  })

  function host(env: NodeJS.ProcessEnv, version = '14.44.35211.0'): VcRedistHost {
    return { env, microsoftFileVersion: () => version }
  }

  it('downloads the pinned redistributable and rejects other bytes', async () => {
    const stage = temporary()
    const urls: string[] = []

    await expect(prepareWindows7VcRedist(stage, host({}), async (url) => {
      urls.push(url)
      return Buffer.from('not the redistributable')
    })).rejects.toThrow(/checksum mismatch/u)

    expect(urls).toEqual([VC_REDIST_URL])
    expect(existsSync(join(stage, 'vc_redist.x64.exe'))).toBe(false)
  })

  it('stages an explicit Microsoft-signed redistributable only when it supports Windows 7', async () => {
    const stage = temporary()
    const source = join(temporary(), 'vc_redist.x64.exe')
    writeFileSync(source, 'MZ')
    const fetchBytes = async (): Promise<Buffer> => { throw new Error('must not download') }

    await expect(prepareWindows7VcRedist(stage, host({ WORKDSH_WIN7_VC_REDIST: source }, '14.42.34433.0'), fetchBytes))
      .resolves.toEqual({ path: join(stage, 'vc_redist.x64.exe'), version: parseFileVersion('14.42.34433.0') })
    await expect(prepareWindows7VcRedist(stage, host({ WORKDSH_WIN7_VC_REDIST: source }, '14.51.36231.0'), fetchBytes))
      .rejects.toThrow(/Windows 7 needs 14\.29-14\.4x/u)
  })

  it('renders NSIS definitions with split version words and escaped paths', () => {
    expect(renderWindows7PayloadInclude({
      vxkexSetup: 'C:\\build\\.win7\\KexSetup_Release_1_2_3_2463.exe',
      vcRedist: 'C:\\$work\\.win7\\vc_redist.x64.exe',
      vcRedistVersion: parseFileVersion('14.44.35211.0'),
    })).toBe([
      '; Generated by scripts/windows7-offline-payload.ts. Do not edit.',
      '!define WORKDSH_BUNDLED_VXKEX "C:\\build\\.win7\\KexSetup_Release_1_2_3_2463.exe"',
      '!define WORKDSH_BUNDLED_VXKEX_LABEL "1.2.3.2463"',
      '!define WORKDSH_BUNDLED_VXKEX_VERSION 0x8000099F',
      '!define WORKDSH_BUNDLED_VCREDIST "C:\\$$work\\.win7\\vc_redist.x64.exe"',
      '!define WORKDSH_BUNDLED_VCREDIST_LABEL "14.44.35211.0"',
      '!define WORKDSH_BUNDLED_VCREDIST_MS 0x000E002C',
      '!define WORKDSH_BUNDLED_VCREDIST_LS 0x898B0000',
      '',
    ].join('\n'))
  })
})
