import { existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import {
  VXKEX_NEXT_INSTALLED_VERSION,
  VXKEX_NEXT_SETUP,
  VXKEX_NEXT_URL,
  VXKEX_NEXT_VERSION,
  bundledVxKexPath,
  prepareBundledVxKex,
} from '../scripts/vxkex-next.ts'
import {
  isWindows7VcRedist,
  locateWindows7VcRedist,
  parseFileVersion,
  renderWindows7PayloadInclude,
  type VcRedistHost,
} from '../scripts/windows7-offline-payload.ts'

const roots: string[] = []
afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true })
})

function temporary(): string {
  const root = mkdtempSync(join(tmpdir(), 'workdsh-win7-payload-'))
  roots.push(root)
  return root
}

describe('pinned VxKex NEXT setup', () => {
  it('pins one release asset and its InstalledVersion encoding', () => {
    expect(VXKEX_NEXT_SETUP).toBe(`KexSetup_Release_${VXKEX_NEXT_VERSION.replaceAll('.', '_')}.exe`)
    expect(VXKEX_NEXT_URL).toBe(`https://github.com/YuZhouRen86/VxKex-NEXT/releases/download/${VXKEX_NEXT_VERSION}/${VXKEX_NEXT_SETUP}`)
    expect(VXKEX_NEXT_INSTALLED_VERSION).toBe(0x8000099f)
  })

  it('rejects downloaded bytes that do not match the pinned digest', async () => {
    const root = temporary()
    const urls: string[] = []

    await expect(prepareBundledVxKex(root, async (url) => {
      urls.push(url)
      return Buffer.from('not the VxKex NEXT setup')
    })).rejects.toThrow(/checksum mismatch/u)

    expect(urls).toEqual([VXKEX_NEXT_URL])
    expect(existsSync(bundledVxKexPath(root))).toBe(false)
  })
})

describe('Windows 7 VC++ redistributable', () => {
  it('parses Windows file versions', () => {
    expect(parseFileVersion('14.44.35211.0')).toEqual({ major: 14, minor: 44, build: 35211, revision: 0 })
    expect(parseFileVersion('14.29.30153')).toEqual({ major: 14, minor: 29, build: 30153, revision: 0 })
    expect(() => parseFileVersion('14.44')).toThrow(/Invalid/u)
  })

  it('accepts only the v14 series that still installs on Windows 7', () => {
    expect(isWindows7VcRedist(parseFileVersion('14.29.30153.0'))).toBe(true)
    expect(isWindows7VcRedist(parseFileVersion('14.44.35211.0'))).toBe(true)
    expect(isWindows7VcRedist(parseFileVersion('14.28.29914.0'))).toBe(false)
    expect(isWindows7VcRedist(parseFileVersion('14.50.35710.0'))).toBe(false)
  })

  function host(root: string, versions: Record<string, string>, env: NodeJS.ProcessEnv = {}): VcRedistHost {
    for (const directory of Object.keys(versions)) {
      if (directory.startsWith('/')) continue
      mkdirSync(join(root, 'VC', 'Redist', 'MSVC', directory), { recursive: true })
      writeFileSync(join(root, 'VC', 'Redist', 'MSVC', directory, 'vc_redist.x64.exe'), 'MZ')
    }
    return {
      env,
      visualStudioRoots: () => [root],
      microsoftFileVersion: (path) => {
        const entry = Object.entries(versions).find(([directory]) => path.includes(directory))
        if (entry === undefined) throw new Error(`unexpected ${path}`)
        return entry[1]
      },
    }
  }

  it('selects the newest Windows 7-capable redistributable from Visual Studio', () => {
    const root = temporary()
    const selected = locateWindows7VcRedist(host(root, {
      '14.38.33130': '14.38.33130.0',
      '14.44.35112': '14.44.35211.0',
      '14.50.35710': '14.50.35710.0',
    }))

    expect(selected.path).toBe(join(root, 'VC', 'Redist', 'MSVC', '14.44.35112', 'vc_redist.x64.exe'))
    expect(selected.version).toEqual({ major: 14, minor: 44, build: 35211, revision: 0 })
  })

  it('uses an explicit redistributable and still rejects one without Windows 7 support', () => {
    const root = temporary()
    expect(locateWindows7VcRedist(host(root, { '/override/vc_redist.x64.exe': '14.42.34433.0' }, {
      WORKDSH_WIN7_VC_REDIST: '/override/vc_redist.x64.exe',
    })).path).toBe('/override/vc_redist.x64.exe')
    expect(() => locateWindows7VcRedist(host(root, { '/override/new.exe': '14.50.35710.0' }, {
      WORKDSH_WIN7_VC_REDIST: '/override/new.exe',
    }))).toThrow(/No Windows 7-capable/u)
  })

  it('renders NSIS definitions with split version words and escaped paths', () => {
    expect(renderWindows7PayloadInclude({
      vxkexSetup: 'C:\\build\\.win7\\KexSetup_Release_1_2_3_2463.exe',
      vcRedist: 'C:\\$work\\.win7\\vc_redist.x64.exe',
      vcRedistVersion: parseFileVersion('14.44.35211.0'),
    })).toBe([
      '; Generated by scripts/windows7-offline-payload.ts. Do not edit.',
      '!define WORKDSH_BUNDLED_VXKEX "C:\\build\\.win7\\KexSetup_Release_1_2_3_2463.exe"',
      '!define WORKDSH_BUNDLED_VXKEX_LABEL "1.2.3.2463"',
      '!define WORKDSH_BUNDLED_VXKEX_VERSION 0x8000099F',
      '!define WORKDSH_BUNDLED_VCREDIST "C:\\$$work\\.win7\\vc_redist.x64.exe"',
      '!define WORKDSH_BUNDLED_VCREDIST_LABEL "14.44.35211.0"',
      '!define WORKDSH_BUNDLED_VCREDIST_MS 0x000E002C',
      '!define WORKDSH_BUNDLED_VCREDIST_LS 0x898B0000',
      '',
    ].join('\n'))
  })
})
