/** Stage the Windows 7 offline installer payload: VxKex NEXT and the VC++ runtime. */

import { spawnSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  VXKEX_NEXT_INSTALLED_VERSION,
  VXKEX_NEXT_VERSION,
  prepareBundledVxKex,
  type FetchBytes,
} from './vxkex-next.ts'

/** A four-part Windows file version. */
export interface FileVersion {
  readonly major: number
  readonly minor: number
  readonly build: number
  readonly revision: number
}

/** Files and versions compiled into `build/installer-win7.nsh`. */
export interface Windows7OfflinePayload {
  readonly vxkexSetup: string
  readonly vcRedist: string
  readonly vcRedistVersion: FileVersion
}

/** Host boundary for locating and authenticating the Microsoft VC++ redistributable. */
export interface VcRedistHost {
  readonly env: NodeJS.ProcessEnv
  /** Visual Studio installation roots, newest first. */
  readonly visualStudioRoots: () => string[]
  /** Authenticode-verify a Microsoft-signed file and return its file version string. */
  readonly microsoftFileVersion: (path: string) => string
}

/** An explicit redistributable path, for machines without Visual Studio. */
export const WINDOWS7_VC_REDIST_OVERRIDE = 'WORKDSH_WIN7_VC_REDIST'

/**
 * Parse a dotted Windows file version.
 * @param text - Version such as `14.44.35211.0`.
 * @returns The four numeric parts.
 */
export function parseFileVersion(text: string): FileVersion {
  const match = /^(\d+)\.(\d+)\.(\d+)(?:\.(\d+))?$/u.exec(text.trim())
  if (match === null) throw new Error(`Invalid Windows file version: ${JSON.stringify(text)}`)
  const [major, minor, build, revision] = [match[1], match[2], match[3], match[4] ?? '0'].map(Number)
  if ([major, minor, build, revision].some(part => part === undefined || part > 0xffff)) {
    throw new Error(`Windows file version part out of range: ${text}`)
  }
  return { major: major!, minor: minor!, build: build!, revision: revision! }
}

/**
 * The VC++ 2015-2022 (v14) runtime series still installs on Windows 7 SP1 up
 * to 14.4x; 14.50 (Visual Studio 2026) requires Windows 10. The Office engine
 * imports `msvcp140_2.dll`, which first shipped in 14.14.
 * @param version - Redistributable file version.
 * @returns Whether it can serve the Windows 7 package.
 */
export function isWindows7VcRedist(version: FileVersion): boolean {
  return version.major === 14 && version.minor >= 29 && version.minor < 50
}

function compareVersions(left: FileVersion, right: FileVersion): number {
  return left.major - right.major || left.minor - right.minor || left.build - right.build || left.revision - right.revision
}

function formatVersion(version: FileVersion): string {
  return `${String(version.major)}.${String(version.minor)}.${String(version.build)}.${String(version.revision)}`
}

function hex(value: number): string {
  return `0x${(value >>> 0).toString(16).toUpperCase().padStart(8, '0')}`
}

/**
 * Choose the redistributable: the explicit override, else the newest
 * Windows 7-capable `vc_redist.x64.exe` shipped with an installed Visual Studio.
 * @param host - Environment, Visual Studio discovery and Authenticode boundary.
 * @returns The redistributable path and its verified version.
 */
export function locateWindows7VcRedist(host: VcRedistHost): { path: string, version: FileVersion } {
  const override = host.env[WINDOWS7_VC_REDIST_OVERRIDE]
  const candidates = override !== undefined && override.length > 0
    ? [override]
    : host.visualStudioRoots().flatMap((root) => {
        const redist = join(root, 'VC', 'Redist', 'MSVC')
        if (!existsSync(redist)) return []
        return readdirSync(redist).map(name => join(redist, name, 'vc_redist.x64.exe')).filter(path => existsSync(path))
      })
  const usable = candidates.flatMap((path) => {
    const version = parseFileVersion(host.microsoftFileVersion(path))
    return isWindows7VcRedist(version) ? [{ path, version }] : []
  }).sort((left, right) => compareVersions(right.version, left.version))
  const selected = usable[0]
  if (selected === undefined) {
    throw new Error(
      `No Windows 7-capable Microsoft vc_redist.x64.exe (14.29-14.4x) was found among ${String(candidates.length)} candidate(s). `
      + `Install the Visual Studio 2022 C++ workload or set ${WINDOWS7_VC_REDIST_OVERRIDE} to a Microsoft-signed vc_redist.x64.exe.`,
    )
  }
  return selected
}

/**
 * Render the NSIS definitions consumed by `build/installer-win7.nsh`.
 * @param payload - Staged files and versions.
 * @returns NSIS source.
 */
export function renderWindows7PayloadInclude(payload: Windows7OfflinePayload): string {
  const quoted = (path: string): string => `"${path.replaceAll('$', '$$$$')}"`
  const { vcRedistVersion: version } = payload
  return [
    '; Generated by scripts/windows7-offline-payload.ts. Do not edit.',
    `!define WORKDSH_BUNDLED_VXKEX ${quoted(payload.vxkexSetup)}`,
    `!define WORKDSH_BUNDLED_VXKEX_LABEL "${VXKEX_NEXT_VERSION}"`,
    `!define WORKDSH_BUNDLED_VXKEX_VERSION ${hex(VXKEX_NEXT_INSTALLED_VERSION)}`,
    `!define WORKDSH_BUNDLED_VCREDIST ${quoted(payload.vcRedist)}`,
    `!define WORKDSH_BUNDLED_VCREDIST_LABEL "${formatVersion(version)}"`,
    `!define WORKDSH_BUNDLED_VCREDIST_MS ${hex(((version.major << 16) | version.minor) >>> 0)}`,
    `!define WORKDSH_BUNDLED_VCREDIST_LS ${hex(((version.build << 16) | version.revision) >>> 0)}`,
    '',
  ].join('\n')
}

function powershell(script: string, env: NodeJS.ProcessEnv): string {
  const result = spawnSync('powershell.exe', ['-NoLogo', '-NoProfile', '-NonInteractive', '-Command', script], {
    encoding: 'utf8',
    env,
    timeout: 120_000,
  })
  if (result.error !== undefined) throw result.error
  if (result.status !== 0) throw new Error(`PowerShell failed (${String(result.status)}): ${result.stderr.trim()}`)
  return result.stdout.trim()
}

/** Native Windows discovery through vswhere and Get-AuthenticodeSignature. */
export function nativeVcRedistHost(env: NodeJS.ProcessEnv = process.env): VcRedistHost {
  return {
    env,
    visualStudioRoots: () => {
      const vswhere = join(env['ProgramFiles(x86)'] ?? 'C:\\Program Files (x86)', 'Microsoft Visual Studio', 'Installer', 'vswhere.exe')
      if (!existsSync(vswhere)) return []
      const result = spawnSync(vswhere, ['-all', '-prerelease', '-products', '*', '-sort', '-property', 'installationPath'], {
        encoding: 'utf8',
        env,
      })
      if (result.error !== undefined || result.status !== 0) return []
      return result.stdout.split(/\r?\n/u).map(line => line.trim()).filter(Boolean)
    },
    microsoftFileVersion: path => powershell([
      `$path = '${path.replaceAll('\'', '\'\'')}'`,
      '$signature = Get-AuthenticodeSignature -LiteralPath $path',
      'if ($signature.Status -ne \'Valid\' -or $signature.SignerCertificate.Subject -notmatch \'O=Microsoft Corporation\') {',
      '  [Console]::Error.WriteLine("$path is not a valid Microsoft-signed file: $($signature.Status)"); exit 3',
      '}',
      '(Get-Item -LiteralPath $path).VersionInfo.FileVersion',
    ].join('\n'), env),
  }
}

/**
 * Stage every file the Windows 7 offline installer compiles in, and its NSIS definitions.
 * @param desktopRoot - Desktop package root.
 * @param host - VC++ redistributable discovery boundary.
 * @param fetchBytes - VxKex download boundary.
 * @returns The staged payload.
 */
export async function prepareWindows7OfflinePayload(
  desktopRoot: string,
  host: VcRedistHost = nativeVcRedistHost(),
  fetchBytes?: FetchBytes,
): Promise<Windows7OfflinePayload> {
  const stage = join(desktopRoot, 'build', '.win7')
  mkdirSync(stage, { recursive: true })
  const vxkexSetup = await prepareBundledVxKex(desktopRoot, fetchBytes)
  const located = locateWindows7VcRedist(host)
  const vcRedist = join(stage, 'vc_redist.x64.exe')
  copyFileSync(located.path, vcRedist)
  const payload = { vxkexSetup, vcRedist, vcRedistVersion: located.version }
  writeFileSync(join(stage, 'offline-payload.nsh'), renderWindows7PayloadInclude(payload))
  return payload
}
