/** Stage the Windows 7 offline installer payload: VxKex NEXT and the VC++ runtime. */

import { spawnSync } from 'node:child_process'
import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { preparePinnedAsset, type FetchBytes } from './pinned-asset.ts'
import {
  VXKEX_NEXT_INSTALLED_VERSION,
  VXKEX_NEXT_VERSION,
  prepareBundledVxKex,
} from './vxkex-next.ts'

/** A four-part Windows file version. */
export interface FileVersion {
  readonly major: number
  readonly minor: number
  readonly build: number
  readonly revision: number
}

/** Files and versions compiled into `build/installer-win7.nsh`. */
export interface Windows7OfflinePayload {
  readonly vxkexSetup: string
  readonly vcRedist: string
  readonly vcRedistVersion: FileVersion
}

/** Host boundary for an explicitly supplied VC++ redistributable. */
export interface VcRedistHost {
  readonly env: NodeJS.ProcessEnv
  /** Authenticode-verify a Microsoft-signed file and return its file version string. */
  readonly microsoftFileVersion: (path: string) => string
}

/** An explicit redistributable path, for builds that cannot download it. */
export const WINDOWS7_VC_REDIST_OVERRIDE = 'WORKDSH_WIN7_VC_REDIST'

/**
 * The last VC++ v14 redistributable of the Visual Studio 2022 stream, which
 * still supports Windows 7 SP1 (with KB3033929). Microsoft's versioned URL
 * embeds the same SHA-256; the 14.50+ stream requires Windows 10.
 */
export const VC_REDIST_VERSION = '14.44.35211.0'
export const VC_REDIST_SHA256 = 'cc0ff0eb1dc3f5188ae6300faef32bf5beeba4bdd6e8e445a9184072096b713b'
export const VC_REDIST_URL = 'https://download.visualstudio.microsoft.com/download/pr/7ebf5fdb-36dc-4145-b0a0-90d3d5990a61/'
  + `${VC_REDIST_SHA256.toUpperCase()}/VC_redist.x64.exe`

/**
 * Parse a dotted Windows file version.
 * @param text - Version such as `14.44.35211.0`.
 * @returns The four numeric parts.
 */
export function parseFileVersion(text: string): FileVersion {
  const match = /^(\d+)\.(\d+)\.(\d+)(?:\.(\d+))?$/u.exec(text.trim())
  if (match === null) throw new Error(`Invalid Windows file version: ${JSON.stringify(text)}`)
  const [major, minor, build, revision] = [match[1], match[2], match[3], match[4] ?? '0'].map(Number)
  if ([major, minor, build, revision].some(part => part === undefined || part > 0xffff)) {
    throw new Error(`Windows file version part out of range: ${text}`)
  }
  return { major: major!, minor: minor!, build: build!, revision: revision! }
}

/**
 * The VC++ v14 series still installs on Windows 7 SP1 up to 14.4x; 14.50
 * (Visual Studio 2026) requires Windows 10. The Office engine imports
 * `msvcp140_2.dll`, which first shipped in 14.14.
 * @param version - Redistributable file version.
 * @returns Whether it can serve the Windows 7 package.
 */
export function isWindows7VcRedist(version: FileVersion): boolean {
  return version.major === 14 && version.minor >= 29 && version.minor < 50
}

function formatVersion(version: FileVersion): string {
  return `${String(version.major)}.${String(version.minor)}.${String(version.build)}.${String(version.revision)}`
}

function hex(value: number): string {
  return `0x${(value >>> 0).toString(16).toUpperCase().padStart(8, '0')}`
}

/**
 * Render the NSIS definitions consumed by `build/installer-win7.nsh`.
 * @param payload - Staged files and versions.
 * @returns NSIS source.
 */
export function renderWindows7PayloadInclude(payload: Windows7OfflinePayload): string {
  const quoted = (path: string): string => `"${path.replaceAll('$', '$$$$')}"`
  const { vcRedistVersion: version } = payload
  return [
    '; Generated by scripts/windows7-offline-payload.ts. Do not edit.',
    `!define WORKDSH_BUNDLED_VXKEX ${quoted(payload.vxkexSetup)}`,
    `!define WORKDSH_BUNDLED_VXKEX_LABEL "${VXKEX_NEXT_VERSION}"`,
    `!define WORKDSH_BUNDLED_VXKEX_VERSION ${hex(VXKEX_NEXT_INSTALLED_VERSION)}`,
    `!define WORKDSH_BUNDLED_VCREDIST ${quoted(payload.vcRedist)}`,
    `!define WORKDSH_BUNDLED_VCREDIST_LABEL "${formatVersion(version)}"`,
    `!define WORKDSH_BUNDLED_VCREDIST_MS ${hex(((version.major << 16) | version.minor) >>> 0)}`,
    `!define WORKDSH_BUNDLED_VCREDIST_LS ${hex(((version.build << 16) | version.revision) >>> 0)}`,
    '',
  ].join('\n')
}

/**
 * Stage the VC++ redistributable: an explicit Microsoft-signed, Windows
 * 7-capable file when the override is set, otherwise the pinned download.
 * @param stage - Staging directory.
 * @param host - Environment and Authenticode boundary for the override.
 * @param fetchBytes - Download boundary.
 * @returns The staged path and its version.
 */
export async function prepareWindows7VcRedist(
  stage: string,
  host: VcRedistHost,
  fetchBytes?: FetchBytes,
): Promise<{ path: string, version: FileVersion }> {
  const path = join(stage, 'vc_redist.x64.exe')
  const override = host.env[WINDOWS7_VC_REDIST_OVERRIDE]
  if (override === undefined || override.length === 0) {
    await preparePinnedAsset(
      { label: `Microsoft VC++ redistributable ${VC_REDIST_VERSION}`, url: VC_REDIST_URL, sha256: VC_REDIST_SHA256 },
      path,
      fetchBytes,
    )
    return { path, version: parseFileVersion(VC_REDIST_VERSION) }
  }
  const version = parseFileVersion(host.microsoftFileVersion(override))
  if (!isWindows7VcRedist(version)) {
    throw new Error(`${WINDOWS7_VC_REDIST_OVERRIDE} is VC++ ${formatVersion(version)}; Windows 7 needs 14.29-14.4x`)
  }
  mkdirSync(stage, { recursive: true })
  copyFileSync(override, path)
  return { path, version }
}

/** Native Windows Authenticode check through Windows PowerShell. */
export function nativeVcRedistHost(env: NodeJS.ProcessEnv = process.env): VcRedistHost {
  return {
    env,
    microsoftFileVersion: (path) => {
      // A PowerShell 7 parent (such as a GitHub Actions step) exports its own
      // PSModulePath, which stops Windows PowerShell from loading its modules.
      const childEnv = Object.fromEntries(Object.entries(env).filter(([name]) => name.toUpperCase() !== 'PSMODULEPATH'))
      const result = spawnSync('powershell.exe', ['-NoLogo', '-NoProfile', '-NonInteractive', '-Command', [
        `$path = '${path.replaceAll('\'', '\'\'')}'`,
        '$signature = Get-AuthenticodeSignature -LiteralPath $path',
        'if ($signature.Status -ne \'Valid\' -or $signature.SignerCertificate.Subject -notmatch \'O=Microsoft Corporation\') {',
        '  [Console]::Error.WriteLine("$path is not a valid Microsoft-signed file: $($signature.Status)"); exit 3',
        '}',
        '(Get-Item -LiteralPath $path).VersionInfo.FileVersion',
      ].join('\n')], { encoding: 'utf8', env: childEnv, timeout: 120_000 })
      if (result.error !== undefined) throw result.error
      if (result.status !== 0) throw new Error(`PowerShell failed (${String(result.status)}): ${result.stderr.trim()}`)
      return result.stdout.trim()
    },
  }
}

/**
 * Stage every file the Windows 7 offline installer compiles in, and its NSIS definitions.
 * @param desktopRoot - Desktop package root.
 * @param host - Override boundary for the VC++ redistributable.
 * @param fetchBytes - Download boundary.
 * @returns The staged payload.
 */
export async function prepareWindows7OfflinePayload(
  desktopRoot: string,
  host: VcRedistHost = nativeVcRedistHost(),
  fetchBytes?: FetchBytes,
): Promise<Windows7OfflinePayload> {
  const stage = join(desktopRoot, 'build', '.win7')
  mkdirSync(stage, { recursive: true })
  const vxkexSetup = await prepareBundledVxKex(desktopRoot, fetchBytes)
  const vcRedist = await prepareWindows7VcRedist(stage, host, fetchBytes)
  const payload = { vxkexSetup, vcRedist: vcRedist.path, vcRedistVersion: vcRedist.version }
  writeFileSync(join(stage, 'offline-payload.nsh'), renderWindows7PayloadInclude(payload))
  return payload
}
